### ISSUE TITLE
Publish it to NPM?

### ISSUE THREAD

**Issue by 7rulnik** [iammerrick/how-to-lazy-load-react-webpack#1]

**Comment by iammerrick** [comment]
Thanks! This repository serves as a reference implementation for the webpack documentation. While I use the code found in this repository in production and it works great I think there are a lot more full-featured libraries out there that are probably more in line with developer expectations about a lazy loading library. 

It looks like @thejameskyle published a really polished and more featured solution for lazy loading:
 [react-loadable](https://github.com/thejameskyle/react-loadable)
